FROM mhart/alpine-node:12

RUN apk add --no-cache make gcc g++ python
RUN apk add --update tzdata
#Change it to your timezone. This'll come handy to monitor logfiles.
ENV TZ=Asia/Kolkata

# Creating Relevant directories. 
# We decide to name our project directory as "smart-contracts"
WORKDIR /smart-contracts
RUN mkdir logs logs/test-network logs/main-network logs/test

# Copy the package.json & lock file & install the relevant packages
COPY src/package.json /smart-contracts/package.json
COPY src/package-lock.json /smart-contracts/package-lock.json
RUN npm install

# Add smart-contract relevant code to directory
COPY src/ /smart-contracts/

# Give executable permission to scripts.
RUN chmod +x ./scripts/*.sh

ENTRYPOINT ["npm", "run"]
CMD ["deploy"]